### ISSUE TITLE
Include submitted_by in run archives

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/rp-archiver#26]

**Comment by nicpottier** [comment]
Weird, didn't even know this was a field. Why do we even have this? This is meant to be like FlowStart I take it?

**Comment by nicpottier** [comment]
Our API doesn't expose this does it?

**Comment by rowanseymour** [comment]
It's only for surveyor runs - but someone asked us to to include it (the username) in exports at one point.

**Comment by rowanseymour** [comment]
The run exports include the username - can we include this in the archive format so we don't have to look it up? I.e. something like `"submitted_by": {"id": 235, "username": "Bob"}`. Or is that going to cause problems for purging users?

**Comment by nicpottier** [comment]
I think we can add it, though don't see the point of adding an id field there. Just the username (which is the email) seems sufficient no? (that id can't be looked up in any way which is why it feels weird to have it in the archive)

**Comment by rowanseymour** [comment]
That's fine - so just a single username/email value
