### ISSUE TITLE
requesting docker image!

### ISSUE THREAD

**Issue by cromulus** [nyaruka/rp-archiver#30]
Thanks!

**Comment by cromulus** [comment]
I put one together here: https://github.com/cromulus/rp-archiver-docker

based heavily off of https://github.com/praekeltfoundation/rp-indexer-docker

**Comment by nicpottier** [comment]
We aren't going to maintain one, but hopefully others can use yours in the future.

**Comment by rudigiesler** [comment]
We've created a docker image build here that we are currently maintaining: https://github.com/praekeltfoundation/rp-archiver-docker
Build: https://hub.docker.com/r/praekeltfoundation/rp-archiver
