### ISSUE TITLE
Removing daily archives from S3

### ISSUE THREAD

**Issue by rudigiesler** [nyaruka/rp-archiver#36]
We are doing a rollup of the individual days into a single month archive https://github.com/nyaruka/rp-archiver/pull/14 , but when doing this we aren't removing the daily archives from S3. And in RapidPro we're not showing the daily archives to the user that have monthly rollups.

Is there a reason for not removing the individual days from S3 after completing the rollup?

**Comment by nicpottier** [comment]
Abundance of caution since this is the only place that data is stored. If you want to add an option to additionally add those I'm fine with that but we will probably continue to keep both. S3 storage is cheap.
