### ISSUE TITLE
Configurable archive length

### ISSUE THREAD

**Issue by tybritten** [nyaruka/rp-archiver#38]
Right now archiver is set to archive messages/runs over 90 days old. We'd like the ability to override that via a config variable (to do shorter periods). Any reason that's not advisable? If it's fine, I can submit a PR for it.

**Comment by nicpottier** [comment]
I *think* this should work with a smaller value but can't guarantee it, can certainly try with your own install for a while to find out. Possible complications are mostly around having runs still be active when they are archived, which in theory is dealt (the archive isn't made) but could get chatty.

**Comment by tybritten** [comment]
I was thinking like 30 days. Can runs last longer than that?

**Comment by nicpottier** [comment]
Technically a run can last forever if someone keeps responding now and then and there's a loop.
