### ISSUE TITLE
Archiver Scheduling Problems

### ISSUE THREAD

**Issue by tybritten** [nyaruka/rp-archiver#43]
Right now archiver is hardcoded to run at startup, then 00:01 UTC every day after that.
A couple problems:
1) We'd like to optionally be able to schedule the archiving off of peak times (for us would be more like 06:00-07:00 UTC)
2) The `naptime` calculations appear to be wrong- it's calculating to sleep from the start time, not from now. So the archive time drifts by as long as it took to archive that day. 

If you're fine with it, I'd like to put a PR in to add an optional start time config item as well as fix the nap calculation.

**Comment by nicpottier** [comment]
Sure thing, both those sound good!

**Comment by tybritten** [comment]
Oooh one more- we'd like to add an exit-on-completion flag so archiver could also be schedulable externally (via cronjob etc)

Ok?

**Comment by nicpottier** [comment]
Yep!

**Comment by tybritten** [comment]
closed by https://github.com/nyaruka/rp-archiver/pull/44
